# Generated by Django 6.0.4 on 2026-04-14 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_is_active_user_is_staff_alter_user_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': '管理者', 'verbose_name_plural': '管理者'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'カテゴリ', 'verbose_name_plural': 'カテゴリ'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': '予約', 'verbose_name_plural': '予約'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'レストラン', 'verbose_name_plural': 'レストラン'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'レビュー', 'verbose_name_plural': 'レビュー'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '会員', 'verbose_name_plural': '会員'},
        ),
    ]
