# Generated by Django 6.0.4 on 2026-04-14 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_category_image_restaurant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_class',
            field=models.CharField(choices=[('free', '無料会員'), ('premium', '有料会員')], default='free', max_length=10, verbose_name='会員区分'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='base.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='base.user')),
            ],
            options={
                'unique_together': {('user', 'restaurant')},
            },
        ),
    ]
